{{- if .Values.env.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "clickhouse.fullname" . }}
  labels:
    app: {{ template "clickhouse.name" . }}
    chart: {{ template "clickhouse.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
{{- range $key, $value := .Values.env.secret }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
{{- end }}
{{- end }}